(() => {
  const updated = "22.09.2026";
  const socialContacts = `<span class="social-contacts"><a href="https://www.instagram.com/ai.creator.mk/" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.tiktok.com/@ai.creator.mk" target="_blank" rel="noopener noreferrer">TikTok</a><a href="https://www.facebook.com/profile.php?id=61593260384114" target="_blank" rel="noopener noreferrer">Facebook</a></span>`;
  const docs = {
    privacy: {
      ru: {
        title: "Политика конфиденциальности",
        eyebrow: "MK AI CREATOR · официальный документ",
        lead: "Как мы собираем, используем, храним и защищаем персональные данные посетителей сайта, покупателей AI‑курсов и пользователей Telegram‑бота.",
        toc: "Содержание",
        sections: [
          ["Общие положения", `<p>Настоящая Политика применяется к сайту MK AI CREATOR, страницам курсов, Telegram‑боту оплаты и связанным каналам поддержки (далее — «Сервисы»).</p><p>Владелец персональных данных обрабатывает сведения в соответствии с применимым законодательством Украины, включая Закон Украины «О защите персональных данных» и нормы об электронной коммерции.</p><div class="contact-card"><code>Владелец данных:</code> AI.Creator.MK<br><code>Контакты:</code> ${socialContacts}</div>`],
          ["Какие данные мы можем получать", `<ul><li>имя, фамилию, никнейм и идентификатор аккаунта;</li><li>e‑mail, номер телефона или иной контакт, если пользователь его сообщает;</li><li>выбранный курс, язык, дату заказа и сведения, необходимые для предоставления доступа;</li><li>квитанцию и данные о платеже: сумму, валюту, дату, назначение и идентификатор транзакции; полные реквизиты банковской карты мы не запрашиваем и не храним;</li><li>переписку со службой поддержки, ответы в боте и отправленные учебные материалы;</li><li>технические данные: IP‑адрес, тип устройства и браузера, язык, дату и время посещения, cookies и события аналитики — только если такие инструменты фактически подключены.</li></ul>`],
          ["Откуда поступают данные", `<p>Мы получаем данные непосредственно от вас при использовании сайта, переходе в Telegram‑бот, оплате, отправке квитанции, обращении за поддержкой или прохождении курса. Ограниченные сведения также могут поступать от Telegram, банка, PayPal, хостинг‑ и аналитических сервисов в объёме, необходимом для их работы.</p>`],
          ["Цели и основания обработки", `<p>Данные используются, чтобы:</p><ul><li>оформить заказ, подтвердить оплату и открыть доступ к выбранному курсу;</li><li>поддерживать работу сайта, бота и учебных каналов;</li><li>отвечать на обращения, предотвращать мошенничество и защищать права пользователей и владельца;</li><li>выполнять требования бухгалтерского, налогового и иного применимого законодательства;</li><li>с вашего отдельного согласия — отправлять новости и маркетинговые сообщения.</li></ul><p>Основаниями являются заключение и исполнение договора, выполнение юридических обязанностей, согласие пользователя и законный интерес в обеспечении безопасности Сервисов.</p>`],
          ["Кому могут передаваться данные", `<p>Данные могут быть доступны только в необходимом объёме поставщикам, которые помогают предоставлять Сервисы: Telegram, банкам и платёжным сервисам (включая PayPal), хостинг‑провайдерам, поставщикам аналитики и технической поддержки. Данные также могут быть раскрыты государственным органам, если этого требует закон.</p><p>Мы не продаём персональные данные.</p>`],
          ["Передача данных за пределы Украины", `<p>Telegram, PayPal, хостинг‑ и другие технические поставщики могут обрабатывать данные в других странах. Используя соответствующий сервис, вы понимаете, что такая передача возможна. Мы выбираем поставщиков, которые заявляют о применении мер защиты данных, и передаём только необходимый объём сведений.</p>`],
          ["Срок хранения", `<p>Данные хранятся не дольше, чем необходимо для предоставления доступа, поддержки, разрешения споров и выполнения требований закона. Платёжные и договорные сведения могут храниться в течение срока, установленного бухгалтерским и налоговым законодательством. После истечения срока данные удаляются или обезличиваются, если их дальнейшее хранение не требуется законом.</p>`],
          ["Cookies и аналитика", `<p>Сайт может использовать технически необходимые cookies для языка и корректной работы, а также аналитику — только если она будет подключена. Необязательные cookies должны применяться после получения согласия там, где это требуется. Пользователь может ограничить cookies в настройках браузера, но отдельные функции сайта могут работать некорректно.</p>`],
          ["Права пользователя", `<p>Вы можете запросить информацию об обработке своих данных, доступ, исправление, удаление или ограничение обработки, отозвать согласие, возразить против обработки и обратиться с жалобой к Уполномоченному Верховной Рады Украины по правам человека или в суд. Отзыв согласия не делает незаконной обработку, выполненную до отзыва.</p>`],
          ["Безопасность", `<p>Мы применяем разумные организационные и технические меры: ограничение доступа, проверку администраторов, защиту аккаунтов и минимизацию собираемых данных. Ни один способ передачи через Интернет не обеспечивает абсолютной безопасности; при выявлении инцидента мы принимаем меры в соответствии с применимым законодательством.</p>`],
          ["Данные детей", `<p>Сервисы не предназначены для самостоятельной покупки лицами младше 18 лет. Если покупка совершается для несовершеннолетнего, её должен оформить родитель или законный представитель. Если вы считаете, что ребёнок передал данные без надлежащего согласия, сообщите нам для проверки и удаления.</p>`],
          ["Изменения и контакты", `<p>Мы можем обновлять Политику при изменении Сервисов или законодательства. Новая редакция действует с даты, указанной на странице, и не уменьшает права пользователя задним числом.</p><div class="contact-card"><code>Запросы о данных:</code> ${socialContacts}</div>`]
        ],
        labels: {updated:"Дата редакции",language:"Основной язык",langValue:"Русский",footer:"© AI.Creator.MK · Политика конфиденциальности"}
      },
      uk: {
        title: "Політика конфіденційності",
        eyebrow: "MK AI CREATOR · офіційний документ",
        lead: "Як ми збираємо, використовуємо, зберігаємо та захищаємо персональні дані відвідувачів сайту, покупців AI‑курсів і користувачів Telegram‑бота.",
        toc: "Зміст",
        sections: [
          ["Загальні положення", `<p>Ця Політика застосовується до сайту MK AI CREATOR, сторінок курсів, Telegram‑бота оплати та пов’язаних каналів підтримки (далі — «Сервіси»).</p><p>Володілець персональних даних обробляє відомості відповідно до застосовного законодавства України, зокрема Закону України «Про захист персональних даних» та норм про електронну комерцію.</p><div class="contact-card"><code>Володілець даних:</code> AI.Creator.MK<br><code>Контакти:</code> ${socialContacts}</div>`],
          ["Які дані ми можемо отримувати", `<ul><li>ім’я, прізвище, нікнейм та ідентифікатор облікового запису;</li><li>e‑mail, номер телефону чи інший контакт, якщо користувач його повідомляє;</li><li>обраний курс, мову, дату замовлення та відомості, необхідні для надання доступу;</li><li>квитанцію й дані про платіж: суму, валюту, дату, призначення та ідентифікатор транзакції; повні реквізити банківської картки ми не запитуємо й не зберігаємо;</li><li>листування з підтримкою, відповіді в боті та надіслані навчальні матеріали;</li><li>технічні дані: IP‑адресу, тип пристрою й браузера, мову, дату та час відвідування, cookies і події аналітики — лише якщо такі інструменти фактично підключені.</li></ul>`],
          ["Звідки надходять дані", `<p>Ми отримуємо дані безпосередньо від вас під час користування сайтом, переходу до Telegram‑бота, оплати, надсилання квитанції, звернення по підтримку або проходження курсу. Обмежені відомості також можуть надходити від Telegram, банку, PayPal, хостинг‑ та аналітичних сервісів в обсязі, потрібному для їх роботи.</p>`],
          ["Цілі та підстави обробки", `<p>Дані використовуються, щоб:</p><ul><li>оформити замовлення, підтвердити оплату та відкрити доступ до обраного курсу;</li><li>підтримувати роботу сайту, бота й навчальних каналів;</li><li>відповідати на звернення, запобігати шахрайству та захищати права користувачів і володільця;</li><li>виконувати вимоги бухгалтерського, податкового та іншого застосовного законодавства;</li><li>за вашою окремою згодою — надсилати новини й маркетингові повідомлення.</li></ul><p>Підставами є укладення та виконання договору, виконання юридичних обов’язків, згода користувача й законний інтерес у забезпеченні безпеки Сервісів.</p>`],
          ["Кому можуть передаватися дані", `<p>Дані можуть бути доступні лише в необхідному обсязі постачальникам, які допомагають надавати Сервіси: Telegram, банкам і платіжним сервісам (зокрема PayPal), хостинг‑провайдерам, постачальникам аналітики й технічної підтримки. Дані також можуть бути розкриті державним органам, якщо цього вимагає закон.</p><p>Ми не продаємо персональні дані.</p>`],
          ["Передача даних за межі України", `<p>Telegram, PayPal, хостинг‑ та інші технічні постачальники можуть обробляти дані в інших країнах. Використовуючи відповідний сервіс, ви розумієте, що така передача можлива. Ми обираємо постачальників, які заявляють про застосування заходів захисту даних, і передаємо лише необхідний обсяг відомостей.</p>`],
          ["Строк зберігання", `<p>Дані зберігаються не довше, ніж потрібно для надання доступу, підтримки, вирішення спорів і виконання вимог закону. Платіжні й договірні відомості можуть зберігатися протягом строку, встановленого бухгалтерським і податковим законодавством. Після спливу строку дані видаляються або знеособлюються, якщо подальше зберігання не вимагається законом.</p>`],
          ["Cookies та аналітика", `<p>Сайт може використовувати технічно необхідні cookies для мови й коректної роботи, а також аналітику — лише якщо її буде підключено. Необов’язкові cookies мають застосовуватися після отримання згоди там, де це потрібно. Користувач може обмежити cookies у налаштуваннях браузера, але окремі функції сайту можуть працювати некоректно.</p>`],
          ["Права користувача", `<p>Ви можете запросити інформацію про обробку своїх даних, доступ, виправлення, видалення чи обмеження обробки, відкликати згоду, заперечити проти обробки та подати скаргу Уповноваженому Верховної Ради України з прав людини або до суду. Відкликання згоди не робить незаконною обробку, здійснену до відкликання.</p>`],
          ["Безпека", `<p>Ми застосовуємо розумні організаційні й технічні заходи: обмеження доступу, перевірку адміністраторів, захист облікових записів і мінімізацію зібраних даних. Жоден спосіб передавання через Інтернет не гарантує абсолютної безпеки; у разі виявлення інциденту ми вживаємо заходів відповідно до застосовного законодавства.</p>`],
          ["Дані дітей", `<p>Сервіси не призначені для самостійної купівлі особами молодше 18 років. Якщо курс купують для неповнолітнього, покупку має оформити один із батьків або законний представник. Якщо ви вважаєте, що дитина передала дані без належної згоди, повідомте нам для перевірки та видалення.</p>`],
          ["Зміни та контакти", `<p>Ми можемо оновлювати Політику в разі зміни Сервісів або законодавства. Нова редакція діє з дати, зазначеної на сторінці, і не зменшує права користувача заднім числом.</p><div class="contact-card"><code>Запити щодо даних:</code> ${socialContacts}</div>`]
        ],
        labels: {updated:"Дата редакції",language:"Основна мова",langValue:"Українська",footer:"© AI.Creator.MK · Політика конфіденційності"}
      },
      en: {
        title: "Privacy Policy",
        eyebrow: "MK AI CREATOR · official document",
        lead: "How we collect, use, retain and protect personal data of website visitors, AI course customers and Telegram bot users.",
        toc: "Contents",
        sections: [
          ["General provisions", `<p>This Policy applies to the MK AI CREATOR website, course pages, payment Telegram bot and related support channels (the “Services”).</p><p>The data controller processes information under applicable Ukrainian law, including the Law of Ukraine “On Personal Data Protection” and electronic commerce rules.</p><div class="contact-card"><code>Data controller:</code> AI.Creator.MK<br><code>Contacts:</code> ${socialContacts}</div>`],
          ["Data we may collect", `<ul><li>name, surname, username and account identifier;</li><li>email, phone number or another contact detail you provide;</li><li>selected course, language, order date and information needed to grant access;</li><li>receipt and payment details such as amount, currency, date, purpose and transaction ID; we do not request or retain full bank card details;</li><li>support correspondence, bot responses and submitted learning materials;</li><li>technical data such as IP address, device and browser type, language, visit date and time, cookies and analytics events, only where these tools are actually enabled.</li></ul>`],
          ["Sources of data", `<p>We receive data directly from you when you use the website, open the Telegram bot, pay, submit a receipt, contact support or take a course. Limited information may also come from Telegram, a bank, PayPal, hosting and analytics providers as needed to operate their services.</p>`],
          ["Purposes and legal grounds", `<p>We use data to:</p><ul><li>process an order, verify payment and grant access to the selected course;</li><li>operate the website, bot and learning channels;</li><li>answer requests, prevent fraud and protect the rights of users and the controller;</li><li>meet applicable accounting, tax and other legal duties;</li><li>send news or marketing messages with your separate consent.</li></ul><p>The legal grounds are entering into and performing a contract, compliance with legal duties, consent and legitimate interests in securing the Services.</p>`],
          ["Data recipients", `<p>Data may be made available only as necessary to providers supporting the Services: Telegram, banks and payment services (including PayPal), hosting providers, analytics and technical support providers. Data may also be disclosed to public authorities where required by law.</p><p>We do not sell personal data.</p>`],
          ["International transfers", `<p>Telegram, PayPal, hosting and other technical providers may process data in other countries. By using the relevant service, you understand that such transfer may occur. We select providers that state they apply data protection measures and disclose only the information necessary for the service.</p>`],
          ["Retention", `<p>Data is kept no longer than necessary to provide access and support, resolve disputes and comply with law. Payment and contractual information may be retained for the period required by accounting and tax laws. After that period, data is deleted or anonymised unless further retention is legally required.</p>`],
          ["Cookies and analytics", `<p>The website may use strictly necessary cookies for language preferences and proper operation, and analytics only if enabled. Optional cookies should be used after consent where required. You may restrict cookies in your browser, although some website functions may then work incorrectly.</p>`],
          ["Your rights", `<p>You may request information about processing, access, correction, deletion or restriction, withdraw consent, object to processing and complain to the Ukrainian Parliament Commissioner for Human Rights or a court. Withdrawal of consent does not affect the lawfulness of processing carried out before withdrawal.</p>`],
          ["Security", `<p>We use reasonable organisational and technical safeguards, including access limits, administrator verification, account protection and data minimisation. No Internet transmission method is completely secure; if an incident is identified, we take steps required by applicable law.</p>`],
          ["Children’s data", `<p>The Services are not intended for independent purchase by persons under 18. Where a course is purchased for a minor, a parent or legal guardian must complete the purchase. If you believe a child provided data without proper consent, contact us so it can be reviewed and deleted.</p>`],
          ["Changes and contact", `<p>We may update this Policy when the Services or law changes. A new version applies from the date shown on the page and does not retroactively reduce user rights.</p><div class="contact-card"><code>Data requests:</code> ${socialContacts}</div>`]
        ],
        labels: {updated:"Version date",language:"Current language",langValue:"English",footer:"© AI.Creator.MK · Privacy Policy"}
      }
    },
    offer: {
      ru: {
        title: "Публичная оферта",
        eyebrow: "MK AI CREATOR · публичная оферта",
        lead: "Условия приобретения и использования цифровых AI‑курсов MK AI CREATOR через сайт и Telegram‑бот.",
        toc: "Содержание",
        sections: [
          ["Статус документа и стороны", `<p>Этот документ является предложением заключить договор о предоставлении информационно‑консультационных услуг и доступа к цифровым учебным материалам. Исполнитель — лицо, указанное ниже. Заказчик — дееспособное физическое лицо, которое выбрало курс и акцептовало Оферту.</p><div class="contact-card"><code>Исполнитель:</code> AI.Creator.MK<br><code>Контакты:</code> ${socialContacts}</div>`],
          ["Предмет договора", `<p>Исполнитель предоставляет Заказчику доступ к выбранному AI‑курсу, учебным материалам, предусмотренным программой, и готовым AI‑агентам, если они включены в описание курса на момент покупки. Точный состав, цена, язык и формат каждого продукта указываются на странице курса и в Telegram‑боте.</p><p>Услуга является образовательной и информационно‑консультационной. Она не гарантирует конкретный доход, количество клиентов, просмотров или иной коммерческий результат.</p>`],
          ["Курсы и цены", `<ul><li>«AI‑модель с нуля» — 9,99 USD вместо 55 USD;</li><li>«AI‑фотосессии» — 9,99 USD вместо 55 USD;</li><li>«AI‑мультфильмы» — 15 USD вместо 65 USD.</li></ul><p>Цена в долларах США фиксируется на момент заказа. Для оплаты на украинскую карту сумма в гривнах рассчитывается по актуальному официальному курсу НБУ, который показывает Telegram‑бот перед оплатой. Из‑за округления итоговая сумма может отличаться на несколько копеек.</p>`],
          ["Оформление заказа и акцепт", `<p>Заказчик выбирает курс и язык на сайте, переходит в Telegram‑бот, проверяет название и цену, выбирает способ оплаты и получает платёжные данные. Акцептом Оферты считается полная оплата выбранного курса после ознакомления с настоящими условиями. Прикрепление квитанции используется для проверки платежа, но само по себе не заменяет оплату.</p>`],
          ["Оплата", `<p>Оплата производится банковским переводом на украинскую карту или через PayPal по реквизитам, показанным в боте. Комиссии банка или платёжного сервиса оплачивает Заказчик, если сервис не указывает иное. Заказчик должен проверить получателя, сумму и назначение до подтверждения перевода и не публиковать платёжные данные.</p>`],
          ["Предоставление доступа", `<p>После поступления оплаты и проверки квитанции Исполнитель предоставляет доступ к соответствующему закрытому каналу, боту или иной учебной среде. Проверка выполняется вручную в разумный срок. Если доступ не получен, Заказчик обращается по контактам Исполнителя и прикладывает сведения о платеже без передачи полного номера карты, CVV или паролей.</p><p>Доступ предоставляется без установленного срока к приобретённой версии курса. При прекращении работы конкретной платформы Исполнитель вправе перенести материалы на другую платформу и сообщить новый способ доступа.</p>`],
          ["Отказ и возврат средств", `<p>Оплачивая курс, Заказчик прямо соглашается на предоставление цифрового контента и начало исполнения договора до истечения срока отказа от дистанционного договора. Заказчик подтверждает, что после предоставления доступа к курсу он утрачивает право отказаться от договора по причинам, не связанным с нарушением Исполнителем своих обязательств.</p><p>Доступ считается предоставленным с момента, когда Исполнитель направил Заказчику ссылку, приглашение, сообщение об открытии доступа либо добавил его в соответствующий бот, канал, кабинет или другую учебную среду. Факт предоставления доступа может подтверждаться сообщениями Telegram, данными бота, журнала действий, электронной перепиской и другими электронными доказательствами. Отсутствие входа в курс или фактического использования материалов по причинам, зависящим от Заказчика, не означает, что доступ не был предоставлен.</p><p><strong>После предоставления доступа к курсу уплаченные средства возврату не подлежат.</strong> В частности, возврат не производится, если Заказчик передумал, не начал или не завершил обучение, не воспользовался предоставленным доступом, субъективно недоволен содержанием или форматом курса, ожидал иной результат либо не получил желаемый доход, количество клиентов, просмотров или иной коммерческий эффект.</p><p>Это условие не ограничивает обязательные права потребителя, предусмотренные законом. Если доступ не работает либо цифровой контент существенно не соответствует заявленному описанию, Заказчик обязан сообщить об этом Исполнителю и предоставить разумный срок для проверки, восстановления доступа, устранения несоответствия или предоставления равноценного способа доступа. Требование о возврате может заявляться только в случаях и порядке, прямо предусмотренных законом, в частности если нарушение возникло по вине Исполнителя и не было устранено в установленный законом срок.</p><p>До предоставления доступа Заказчик может обратиться с запросом об отмене заказа. Любое требование должно содержать имя, дату и способ оплаты, название курса, описание обстоятельств и подтверждение платежа без передачи полного номера карты, CVV или паролей.</p>`],
          ["Права и обязанности заказчика", `<p>Заказчик обязуется предоставить корректные данные, обеспечить совместимое устройство и Интернет, самостоятельно соблюдать правила сторонних AI‑сервисов и не передавать доступ третьим лицам. Заказчик вправе получить оплаченный доступ, понятную информацию о продукте и поддержку по вопросам доступа.</p>`],
          ["Интеллектуальная собственность", `<p>Учебные видео, тексты, промпты, шаблоны, AI‑агенты, графика и иные материалы защищены авторским правом. Покупателю предоставляется личное, неисключительное и непередаваемое право использовать их для собственного обучения и создания своего контента.</p><p>Запрещены перепродажа, публикация, массовое копирование, передача доступа, создание и распространение копии курса или удаление обозначений правообладателя без письменного разрешения. Это не ограничивает законные способы использования, прямо разрешённые законом.</p>`],
          ["Сторонние сервисы и AI", `<p>Для обучения могут использоваться сторонние платформы и AI‑инструменты. Их доступность, тарифы, лимиты и правила устанавливают соответствующие поставщики и могут меняться независимо от Исполнителя. Заказчик самостоятельно принимает условия этих сервисов и отвечает за законность загружаемых материалов и полученного контента.</p>`],
          ["Ответственность и форс‑мажор", `<p>Стороны отвечают в пределах применимого законодательства. Исполнитель не отвечает за сбои Интернета, устройства Заказчика, Telegram, банков, PayPal или сторонних AI‑сервисов, но помогает восстановить доступ, когда это возможно.</p><p>Сторона освобождается от ответственности за нарушение, вызванное чрезвычайными и непредотвратимыми обстоятельствами, на период их действия, при условии разумного уведомления другой стороны.</p>`],
          ["Персональные данные", `<p>Персональные данные обрабатываются для оформления заказа, подтверждения оплаты, предоставления доступа и поддержки в соответствии с Политикой конфиденциальности. Передавая квитанцию, Заказчик должен скрыть лишние банковские сведения, не нужные для проверки платежа.</p>`],
          ["Претензии и споры", `<p>Сначала стороны стараются решить вопрос путём обращения в поддержку. Если договориться не удалось, спор рассматривается по законодательству Украины компетентным судом с сохранением всех обязательных прав потребителя.</p><div class="contact-card"><code>Контакты для обращений:</code> ${socialContacts}</div>`],
          ["Срок действия и изменения", `<p>Оферта действует с даты публикации. Редакция, принятая при оплате, применяется к соответствующему заказу. Изменения для будущих заказов публикуются в новой редакции и не применяются задним числом к уже оплаченным услугам, если иное не требуется законом или не согласовано сторонами.</p>`]
        ],
        labels: {updated:"Дата редакции",language:"Основной язык",langValue:"Русский",footer:"© AI.Creator.MK · Публичная оферта"}
      },
      uk: {
        title: "Публічна оферта",
        eyebrow: "MK AI CREATOR · публічна оферта",
        lead: "Умови придбання та використання цифрових AI‑курсів MK AI CREATOR через сайт і Telegram‑бот.",
        toc: "Зміст",
        sections: [
          ["Статус документа та сторони", `<p>Цей документ є пропозицією укласти договір про надання інформаційно‑консультаційних послуг і доступу до цифрових навчальних матеріалів. Виконавець — особа, зазначена нижче. Замовник — дієздатна фізична особа, яка обрала курс і акцептувала Оферту.</p><div class="contact-card"><code>Виконавець:</code> AI.Creator.MK<br><code>Контакти:</code> ${socialContacts}</div>`],
          ["Предмет договору", `<p>Виконавець надає Замовнику доступ до обраного AI‑курсу, навчальних матеріалів, передбачених програмою, та готових AI‑агентів, якщо вони включені до опису курсу на момент купівлі. Точний склад, ціна, мова та формат кожного продукту зазначаються на сторінці курсу й у Telegram‑боті.</p><p>Послуга є освітньою та інформаційно‑консультаційною. Вона не гарантує конкретного доходу, кількості клієнтів, переглядів чи іншого комерційного результату.</p>`],
          ["Курси та ціни", `<ul><li>«AI‑модель з нуля» — 9,99 USD замість 55 USD;</li><li>«AI‑фотосесії» — 9,99 USD замість 55 USD;</li><li>«AI‑мультфільми» — 15 USD замість 65 USD.</li></ul><p>Ціна в доларах США фіксується на момент замовлення. Для оплати на українську картку сума в гривнях розраховується за актуальним офіційним курсом НБУ, який показує Telegram‑бот перед оплатою. Через округлення підсумкова сума може відрізнятися на кілька копійок.</p>`],
          ["Оформлення замовлення та акцепт", `<p>Замовник обирає курс і мову на сайті, переходить до Telegram‑бота, перевіряє назву й ціну, обирає спосіб оплати та отримує платіжні дані. Акцептом Оферти є повна оплата обраного курсу після ознайомлення з цими умовами. Прикріплення квитанції використовується для перевірки платежу, але саме по собі не замінює оплату.</p>`],
          ["Оплата", `<p>Оплата здійснюється банківським переказом на українську картку або через PayPal за реквізитами, показаними в боті. Комісії банку чи платіжного сервісу сплачує Замовник, якщо сервіс не зазначає інше. Замовник має перевірити одержувача, суму та призначення до підтвердження переказу й не публікувати платіжні дані.</p>`],
          ["Надання доступу", `<p>Після надходження оплати та перевірки квитанції Виконавець надає доступ до відповідного закритого каналу, бота або іншого навчального середовища. Перевірка виконується вручну в розумний строк. Якщо доступ не отримано, Замовник звертається за контактами Виконавця і додає відомості про платіж без передавання повного номера картки, CVV або паролів.</p><p>Доступ надається без установленого строку до придбаної версії курсу. Якщо конкретна платформа припиняє роботу, Виконавець має право перенести матеріали на іншу платформу та повідомити новий спосіб доступу.</p>`],
          ["Відмова та повернення коштів", `<p>Оплачуючи курс, Замовник прямо погоджується на надання цифрового контенту та початок виконання договору до закінчення строку відмови від дистанційного договору. Замовник підтверджує, що після надання доступу до курсу він втрачає право відмовитися від договору з причин, не пов’язаних із порушенням Виконавцем своїх зобов’язань.</p><p>Доступ вважається наданим з моменту, коли Виконавець надіслав Замовнику посилання, запрошення, повідомлення про відкриття доступу або додав його до відповідного бота, каналу, кабінету чи іншого навчального середовища. Факт надання доступу може підтверджуватися повідомленнями Telegram, даними бота, журналу дій, електронним листуванням та іншими електронними доказами. Відсутність входу до курсу або фактичного використання матеріалів із причин, що залежать від Замовника, не означає, що доступ не було надано.</p><p><strong>Після надання доступу до курсу сплачені кошти поверненню не підлягають.</strong> Зокрема, повернення не здійснюється, якщо Замовник передумав, не розпочав або не завершив навчання, не скористався наданим доступом, суб’єктивно незадоволений змістом чи форматом курсу, очікував іншого результату або не отримав бажаного доходу, кількості клієнтів, переглядів чи іншого комерційного ефекту.</p><p>Ця умова не обмежує обов’язкові права споживача, передбачені законом. Якщо доступ не працює або цифровий контент істотно не відповідає заявленому опису, Замовник зобов’язаний повідомити про це Виконавця та надати розумний строк для перевірки, відновлення доступу, усунення невідповідності або надання рівноцінного способу доступу. Вимога про повернення може заявлятися лише у випадках і порядку, прямо передбачених законом, зокрема якщо порушення виникло з вини Виконавця й не було усунуто у встановлений законом строк.</p><p>До надання доступу Замовник може звернутися із запитом про скасування замовлення. Будь-яка вимога має містити ім’я, дату й спосіб оплати, назву курсу, опис обставин і підтвердження платежу без передавання повного номера картки, CVV або паролів.</p>`],
          ["Права та обов’язки замовника", `<p>Замовник зобов’язується надати коректні дані, забезпечити сумісний пристрій та Інтернет, самостійно дотримуватися правил сторонніх AI‑сервісів і не передавати доступ третім особам. Замовник має право отримати оплачений доступ, зрозумілу інформацію про продукт і підтримку з питань доступу.</p>`],
          ["Інтелектуальна власність", `<p>Навчальні відео, тексти, промпти, шаблони, AI‑агенти, графіка та інші матеріали захищені авторським правом. Покупцеві надається особисте, невиключне й непередаване право використовувати їх для власного навчання та створення свого контенту.</p><p>Заборонені перепродаж, публікація, масове копіювання, передавання доступу, створення й поширення копії курсу або видалення позначень правовласника без письмового дозволу. Це не обмежує законні способи використання, прямо дозволені законом.</p>`],
          ["Сторонні сервіси та AI", `<p>Для навчання можуть використовуватися сторонні платформи та AI‑інструменти. Їх доступність, тарифи, ліміти й правила встановлюють відповідні постачальники та можуть змінюватися незалежно від Виконавця. Замовник самостійно приймає умови цих сервісів і відповідає за законність завантажених матеріалів та отриманого контенту.</p>`],
          ["Відповідальність і форс‑мажор", `<p>Сторони відповідають у межах застосовного законодавства. Виконавець не відповідає за збої Інтернету, пристрою Замовника, Telegram, банків, PayPal чи сторонніх AI‑сервісів, але допомагає відновити доступ, коли це можливо.</p><p>Сторона звільняється від відповідальності за порушення, спричинене надзвичайними й невідворотними обставинами, на період їх дії за умови розумного повідомлення іншої сторони.</p>`],
          ["Персональні дані", `<p>Персональні дані обробляються для оформлення замовлення, підтвердження оплати, надання доступу й підтримки відповідно до Політики конфіденційності. Передаючи квитанцію, Замовник має приховати зайві банківські відомості, які не потрібні для перевірки платежу.</p>`],
          ["Претензії та спори", `<p>Спочатку сторони намагаються вирішити питання шляхом звернення до підтримки. Якщо домовитися не вдалося, спір розглядається за законодавством України компетентним судом зі збереженням усіх обов’язкових прав споживача.</p><div class="contact-card"><code>Контакти для звернень:</code> ${socialContacts}</div>`],
          ["Строк дії та зміни", `<p>Оферта діє з дати публікації. Редакція, прийнята під час оплати, застосовується до відповідного замовлення. Зміни для майбутніх замовлень публікуються в новій редакції й не застосовуються заднім числом до вже оплачених послуг, якщо інше не вимагається законом або не погоджено сторонами.</p>`]
        ],
        labels: {updated:"Дата редакції",language:"Основна мова",langValue:"Українська",footer:"© AI.Creator.MK · Публічна оферта"}
      },
      en: {
        title: "Public Offer Agreement",
        eyebrow: "MK AI CREATOR · public offer agreement",
        lead: "Terms for purchasing and using MK AI CREATOR digital AI courses through the website and Telegram bot.",
        toc: "Contents",
        sections: [
          ["Document status and parties", `<p>This document is an offer to enter into an agreement for information and consulting services and access to digital learning materials. The Provider is the person identified below. The Customer is a legally capable individual who selects a course and accepts this Offer.</p><div class="contact-card"><code>Provider:</code> AI.Creator.MK<br><code>Contacts:</code> ${socialContacts}</div>`],
          ["Subject matter", `<p>The Provider grants the Customer access to the selected AI course, the learning materials included in its programme and ready-made AI agents where they are included in the course description at the time of purchase. The exact content, price, language and format of each product are stated on the course page and in the Telegram bot.</p><p>The service is educational and informational. It does not guarantee a specific income, number of clients, views or other commercial result.</p>`],
          ["Courses and prices", `<ul><li>“AI Model from Scratch” — USD 9.99 instead of USD 55;</li><li>“AI Photoshoots” — USD 9.99 instead of USD 55;</li><li>“AI Cartoons” — USD 15 instead of USD 65.</li></ul><p>The US dollar price is fixed when the order is placed. For payment to a Ukrainian card, the hryvnia amount is calculated using the current official NBU exchange rate shown by the Telegram bot before payment. Rounding may cause a minor difference in the final amount.</p>`],
          ["Ordering and acceptance", `<p>The Customer selects the course and language on the website, opens the Telegram bot, checks the title and price, chooses a payment method and receives payment details. The Offer is accepted by full payment for the selected course after reviewing these terms. Uploading a receipt is used to verify payment but does not itself replace payment.</p>`],
          ["Payment", `<p>Payment is made by bank transfer to a Ukrainian card or through PayPal using details shown in the bot. Bank or payment-service fees are paid by the Customer unless the service states otherwise. The Customer must verify the recipient, amount and payment reference before confirming the transfer and must not publish payment details.</p>`],
          ["Access delivery", `<p>After the payment is received and the receipt is checked, the Provider grants access to the relevant private channel, bot or other learning environment. Verification is performed manually within a reasonable time. If access is not received, the Customer should contact the Provider and provide payment information without sharing a full card number, CVV or passwords.</p><p>Access to the purchased version of the course is granted without a fixed end date. If a particular platform ceases operation, the Provider may migrate materials to another platform and communicate the new access method.</p>`],
          ["Cancellation and refunds", `<p>By paying for a course, the Customer expressly consents to the supply of digital content and performance of the agreement beginning before the expiry of any withdrawal period applicable to a distance contract. The Customer acknowledges that, once access to the course is provided, the Customer loses the right to withdraw for reasons unrelated to the Provider’s breach.</p><p>Access is deemed provided when the Provider sends the Customer a link, invitation or access confirmation, or adds the Customer to the relevant bot, channel, account or other learning environment. Delivery may be evidenced by Telegram messages, bot records, activity logs, electronic correspondence and other electronic evidence. Failure to enter the course or use the materials for reasons attributable to the Customer does not mean that access was not provided.</p><p><strong>Once access to the course has been provided, all payments are non-refundable.</strong> In particular, no refund is due where the Customer changes their mind, does not start or complete the course, does not use the access provided, is subjectively dissatisfied with the content or format, expected a different result, or fails to achieve a desired level of income, clients, views or any other commercial outcome.</p><p>This clause does not limit mandatory consumer rights under applicable law. If access does not work or the digital content materially fails to conform to its stated description, the Customer must notify the Provider and allow a reasonable period to investigate, restore access, remedy the non-conformity or provide an equivalent access method. A refund may be claimed only in the cases and manner expressly required by law, including where a failure attributable to the Provider has not been remedied within the period required by law.</p><p>Before access is provided, the Customer may request cancellation. Any claim must state the Customer’s name, payment date and method, course title, relevant circumstances and proof of payment without disclosing a full card number, CVV or passwords.</p>`],
          ["Customer rights and duties", `<p>The Customer must provide accurate information, maintain a compatible device and Internet connection, follow third-party AI service rules and refrain from sharing access. The Customer is entitled to paid access, clear product information and support concerning access.</p>`],
          ["Intellectual property", `<p>Learning videos, texts, prompts, templates, AI agents, graphics and other materials are protected by copyright. The Customer receives a personal, non-exclusive and non-transferable right to use them for personal learning and creation of the Customer’s own content.</p><p>Resale, publication, bulk copying, access sharing, creation or distribution of a course copy, or removal of rights notices without written permission is prohibited. This does not restrict uses expressly permitted by law.</p>`],
          ["Third-party services and AI", `<p>Training may involve third-party platforms and AI tools. Their availability, pricing, limits and rules are controlled by their providers and may change independently of the Provider. The Customer accepts those services’ terms and is responsible for the lawfulness of uploaded materials and generated content.</p>`],
          ["Liability and force majeure", `<p>The parties are liable within the limits of applicable law. The Provider is not responsible for failures of the Customer’s Internet connection or device, Telegram, banks, PayPal or third-party AI services, but will assist with restoring access where reasonably possible.</p><p>A party is excused from liability for a breach caused by extraordinary and unavoidable circumstances for their duration, provided the other party is reasonably notified.</p>`],
          ["Personal data", `<p>Personal data is processed to place the order, verify payment, grant access and provide support under the Privacy Policy. When submitting a receipt, the Customer should conceal unnecessary banking details that are not needed to verify payment.</p>`],
          ["Claims and disputes", `<p>The parties first seek to resolve issues through support. If no agreement is reached, the dispute is governed by Ukrainian law and heard by a competent court, with all mandatory consumer rights preserved.</p><div class="contact-card"><code>Contact for claims:</code> ${socialContacts}</div>`],
          ["Term and amendments", `<p>The Offer takes effect on publication. The version accepted at payment applies to that order. Changes for future orders are published as a new version and do not retroactively apply to paid services unless required by law or agreed by the parties.</p>`]
        ],
        labels: {updated:"Version date",language:"Current language",langValue:"English",footer:"© AI.Creator.MK · Public Offer Agreement"}
      }
    }
  };

  const type = document.body.dataset.document;
  const supported = ["ru", "uk", "en"];
  const queryLang = new URLSearchParams(location.search).get("lang");
  let lang = supported.includes(queryLang) ? queryLang : "ru";

  function render() {
    const data = docs[type][lang];
    document.documentElement.lang = lang;
    document.title = `${data.title} — MK AI CREATOR`;
    document.getElementById("hero").innerHTML = `<p class="eyebrow">${data.eyebrow}</p><h1 class="gradient-text">${data.title}</h1><p class="lead">${data.lead}</p><div class="meta"><div class="meta-item"><span class="meta-label">${data.labels.updated}</span><span class="meta-value">${updated}</span></div><div class="meta-item"><span class="meta-label">${data.labels.language}</span><span class="meta-value">${data.labels.langValue}</span></div></div>`;
    document.getElementById("toc").innerHTML = `<p class="toc-title">${data.toc}</p><ol>${data.sections.map((s, i) => `<li><a href="#section-${i + 1}">${s[0]}</a></li>`).join("")}</ol>`;
    document.getElementById("document").innerHTML = data.sections.map((s, i) => `<section class="section" id="section-${i + 1}"><h2><span class="number">${String(i + 1).padStart(2, "0")}</span>${s[0]}</h2>${s[1]}</section>`).join("");
    document.getElementById("footer").textContent = data.labels.footer;
    document.querySelectorAll("[data-lang]").forEach(btn => {
      const active = btn.dataset.lang === lang;
      btn.classList.toggle("is-active", active);
      btn.setAttribute("aria-pressed", String(active));
    });
    history.replaceState(null, "", `${location.pathname}?lang=${lang}`);
  }

  document.querySelectorAll("[data-lang]").forEach(btn => btn.addEventListener("click", () => {
    lang = btn.dataset.lang;
    render();
    window.scrollTo({top: 0, behavior: "smooth"});
  }));

  render();
})();
